import os
import re

import pandas as pd
import plotly.express as px

from groq import Groq
from dotenv import load_dotenv


# ============================================================
# ENVIRONMENT
# ============================================================

load_dotenv()


# ============================================================
# GROQ CLIENT
# ============================================================

def get_groq_client():

    api_key = os.getenv("GROQ_API_KEY")

    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not set. "
            "Please add your Groq API key to .env"
        )

    return Groq(api_key=api_key)


# ============================================================
# CLEAN CODE
# ============================================================

def clean_generated_code(code):

    if code is None:
        return ""

    code = str(code).strip()

    # Remove markdown fences
    code = re.sub(
        r"```python",
        "",
        code,
        flags=re.IGNORECASE
    )

    code = re.sub(
        r"```",
        "",
        code
    )

    lines = code.splitlines()

    cleaned_lines = []

    for line in lines:

        stripped = line.strip()

        # Remove imports generated by Groq
        if stripped.startswith("import "):
            continue

        if stripped.startswith("from "):
            continue

        cleaned_lines.append(line)

    return "\n".join(
        cleaned_lines
    ).strip()


# ============================================================
# GENERATE ANALYSIS CODE
# ============================================================

def generate_analysis_code(df, question):

    client = get_groq_client()

    columns = list(df.columns)

    dtypes = {
        column: str(df[column].dtype)
        for column in df.columns
    }

    sample_data = df.head(8).to_string(
        index=False
    )

    # IMPORTANT:
    # Do NOT use an f-string here.
    # Do NOT use .format() here.
    # This prevents curly-brace errors.

    prompt = (
        "You are an expert Python data analyst.\n\n"

        "You have a pandas DataFrame called df.\n\n"

        "AVAILABLE COLUMNS:\n"
        + str(columns)
        + "\n\n"

        "DATA TYPES:\n"
        + str(dtypes)
        + "\n\n"

        "SAMPLE DATA:\n"
        + sample_data
        + "\n\n"

        "USER QUESTION:\n"
        + question
        + "\n\n"

        "YOUR TASK:\n"
        "Generate Python/Pandas code that answers "
        "the user's question using the REAL dataframe.\n\n"

        "IMPORTANT RULES:\n"
        "1. The dataframe already exists as df.\n"
        "2. Pandas is already available as pd.\n"
        "3. Do NOT write import statements.\n"
        "4. Do NOT write import pandas as pd.\n"
        "5. Do NOT load files.\n"
        "6. Do NOT create fake data.\n"
        "7. Do NOT invent values.\n"
        "8. Do NOT use print().\n"
        "9. Do NOT use input().\n"
        "10. Do NOT use exec().\n"
        "11. Do NOT use eval().\n"
        "12. Do NOT use web requests.\n"
        "13. Use only columns that exist.\n"
        "14. Store the final answer in a variable called result.\n"
        "15. Return ONLY executable Python code.\n"
        "16. Do not return markdown.\n"
        "17. Do not explain the code.\n\n"

        "DATE RULES:\n"
        "If the question involves dates, months, quarters, "
        "years, growth, trends, or previous periods, "
        "identify the appropriate date column and use "
        "pd.to_datetime().\n\n"

        "IMPORTANT QUARTER GROWTH RULE:\n"
        "If the user asks: Which region grew fastest last quarter?\n\n"

        "You must:\n"
        "1. Find the date column.\n"
        "2. Convert the date column to datetime.\n"
        "3. Create a quarter using .dt.to_period('Q').\n"
        "4. Find the latest quarter in the dataset.\n"
        "5. Find the previous quarter.\n"
        "6. Calculate sales by Region for the latest quarter.\n"
        "7. Calculate sales by Region for the previous quarter.\n"
        "8. Calculate percentage growth.\n"
        "9. Ignore regions where previous sales are zero.\n"
        "10. Sort by growth percentage descending.\n"
        "11. Return the fastest-growing region.\n\n"

        "The result should contain these fields:\n"
        "Region\n"
        "Previous_Sales\n"
        "Current_Sales\n"
        "Growth_Percentage\n\n"

        "Example quarter logic:\n\n"

        "df['Order_Date'] = pd.to_datetime(df['Order_Date'])\n\n"

        "df['Quarter'] = df['Order_Date'].dt.to_period('Q')\n\n"

        "latest_quarter = df['Quarter'].max()\n\n"

        "previous_quarter = latest_quarter - 1\n\n"

        "current_sales = (\n"
        "    df[df['Quarter'] == latest_quarter]\n"
        "    .groupby('Region')['Sales']\n"
        "    .sum()\n"
        ")\n\n"

        "previous_sales = (\n"
        "    df[df['Quarter'] == previous_quarter]\n"
        "    .groupby('Region')['Sales']\n"
        "    .sum()\n"
        ")\n\n"

        "growth = pd.concat(\n"
        "    [previous_sales, current_sales],\n"
        "    axis=1,\n"
        "    keys=['Previous_Sales', 'Current_Sales']\n"
        ")\n\n"

        "growth = growth.dropna()\n\n"

        "growth = growth[\n"
        "    growth['Previous_Sales'] != 0\n"
        "]\n\n"

        "growth['Growth_Percentage'] = (\n"
        "    (growth['Current_Sales'] - "
        "growth['Previous_Sales'])\n"
        "    / growth['Previous_Sales']\n"
        ") * 100\n\n"

        "growth = growth.reset_index()\n\n"

        "result = (\n"
        "    growth\n"
        "    .sort_values("
        "'Growth_Percentage', "
        "ascending=False"
        ")\n"
        "    .head(1)\n"
        ")\n\n"

        "OTHER EXAMPLES:\n\n"

        "Total sales:\n"
        "result = df['Sales'].sum()\n\n"

        "Highest sales region:\n"
        "result = (\n"
        "    df.groupby('Region')['Sales']\n"
        "    .sum()\n"
        "    .sort_values(ascending=False)\n"
        "    .head(1)\n"
        ")\n\n"

        "Top 5 products:\n"
        "result = (\n"
        "    df.groupby('Product')['Sales']\n"
        "    .sum()\n"
        "    .sort_values(ascending=False)\n"
        "    .head(5)\n"
        ")\n\n"

        "Average sales:\n"
        "result = df['Sales'].mean()\n\n"

        "If required data does not exist, use:\n"
        "result = 'Required data is not available in the dataset.'\n\n"

        "Return ONLY Python code."
    )

    response = client.chat.completions.create(

        model="llama-3.3-70b-versatile",

        messages=[

            {
                "role": "system",
                "content": (
                    "You are an accurate Python Pandas "
                    "data analyst. Return only executable "
                    "Python code."
                )
            },

            {
                "role": "user",
                "content": prompt
            }

        ],

        temperature=0
    )

    code = response.choices[0].message.content

    return clean_generated_code(code)


# ============================================================
# EXECUTE ANALYSIS
# ============================================================

def execute_analysis(df, generated_code):

    try:

        generated_code = clean_generated_code(
            generated_code
        )

        forbidden_words = [

            "import ",

            "__import__",

            "os.",

            "sys.",

            "subprocess",

            "requests.",

            "urllib",

            "open(",

            "eval(",

            "exec(",

            "input(",

            "socket",

            "shutil",

            "pathlib"
        ]

        code_lower = generated_code.lower()

        for word in forbidden_words:

            if word.lower() in code_lower:

                return (
                    None,
                    None,
                    "Generated code contains blocked operation: "
                    + word
                )

        safe_builtins = {

            "len": len,

            "str": str,

            "int": int,

            "float": float,

            "round": round,

            "min": min,

            "max": max,

            "sum": sum,

            "abs": abs,

            "sorted": sorted,

            "range": range,

            "list": list,

            "dict": dict,

            "set": set,

            "enumerate": enumerate
        }

        safe_globals = {

            "__builtins__": safe_builtins,

            "pd": pd
        }

        safe_locals = {

            "df": df.copy(),

            "pd": pd
        }

        exec(
            generated_code,
            safe_globals,
            safe_locals
        )

        result = safe_locals.get(
            "result"
        )

        if result is None:

            return (
                None,
                None,
                "Generated code did not create "
                "a result variable."
            )

        fig = create_visualization(
            result
        )

        return (
            result,
            fig,
            None
        )

    except Exception as e:

        return (
            None,
            None,
            str(e)
        )


# ============================================================
# VISUALIZATION
# ============================================================

def create_visualization(result):

    try:

        if isinstance(
            result,
            pd.DataFrame
        ):

            if result.empty:
                return None

            numeric_columns = (
                result
                .select_dtypes(
                    include="number"
                )
                .columns
                .tolist()
            )

            if (
                len(result.columns) >= 2
                and len(numeric_columns) >= 1
            ):

                x_column = result.columns[0]

                y_column = numeric_columns[0]

                return px.bar(

                    result,

                    x=x_column,

                    y=y_column,

                    title="Analysis Result"
                )

        elif isinstance(
            result,
            pd.Series
        ):

            if result.empty:
                return None

            data = result.reset_index()

            if data.shape[1] >= 2:

                return px.bar(

                    data,

                    x=data.columns[0],

                    y=data.columns[1],

                    title="Analysis Result"
                )

    except Exception:

        return None

    return None


# ============================================================
# AI ANSWER
# ============================================================

def generate_answer(question, result):

    client = get_groq_client()

    if isinstance(
        result,
        pd.DataFrame
    ):

        result_text = result.to_string(
            index=False
        )

    elif isinstance(
        result,
        pd.Series
    ):

        result_text = result.to_string()

    else:

        result_text = str(
            result
        )

    prompt = (

        "You are an AI data analyst.\n\n"

        "USER QUESTION:\n"
        + question
        + "\n\n"

        "ACTUAL COMPUTED RESULT:\n"
        + result_text
        + "\n\n"

        "Answer using ONLY the actual computed result.\n\n"

        "Rules:\n"
        "1. Do not invent numbers.\n"
        "2. Do not change numbers.\n"
        "3. Do not make unsupported assumptions.\n"
        "4. Clearly state the important result.\n"
        "5. Keep the answer concise.\n"
        "6. Mention growth percentage when available.\n"
        "7. Mention previous and current values when available.\n"
        "8. If data is unavailable, say so clearly."
    )

    response = client.chat.completions.create(

        model="llama-3.3-70b-versatile",

        messages=[

            {
                "role": "system",
                "content": (
                    "Explain computed data accurately. "
                    "Never invent numerical results."
                )
            },

            {
                "role": "user",
                "content": prompt
            }

        ],

        temperature=0
    )

    return response.choices[0].message.content.strip()